### ISSUE TITLE
New Maintainer(s) Needed

### ISSUE THREAD

**Issue by ejohn20** [dependency-check/azuredevops#137]
Please let us know if you'd like to take over the primary maintenance of this  extension. We can work with you to migrate the deployment pipelines over to your AZDO org and get you access to publish new extensions.

**Comment by pippolino** [comment]
> Please let us know if you'd like to take over the primary maintenance of this extension. We can work with you to migrate the deployment pipelines over to your AZDO org and get you access to publish new extensions.

Ciao, we are available for main maintenance of the extension.

**Comment by ejohn20** [comment]
@jeremylong are you good with me adding @pippolino as a maintainer on the repo?

**Comment by tlogik** [comment]
@ejohn20 I would like to co-maintain this repo.
Optimally i will do this as part of an organisation i work for since we are using this extension very much.

**Comment by jeremylong** [comment]
@ejohn20 sorry - missed this. I'm fine with anyone that wants to help out on this. I do not use nor have time to assist with this integration.

**Comment by Saturate** [comment]
@ejohn20 I wouldn't mind joining along side @tlogik - representing the same org, and my own :)

**Comment by tlogik** [comment]
hi @ejohn20 
Thanks for allowing me&us to become maintainers.

Adressing the Microsoft account:
brunsviger [at] hotmail [dot] com 

In relation to the transfer of org.
We are currently using this extension for all our pipelines so i think I will try and see if we can (in my org) create a devops org aimed at open source work.
Ill get back asap on that.

For the current setup i would ofc. very much like to approve PR 145 so we can support local cache analysis withut OOM exceptions.

**Comment by ejohn20** [comment]
@Saturate - added you as a maintainer. 

@tlogik - can you confirm that you can sign into this URL: https://marketplace.visualstudio.com/manage with the email address you provided above? The marketplace is giving me an invalid domain error. Can you sign in and grab the user id from the top nav bar (https://learn.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension?view=vs-2022#troubleshoot-adding-a-user-to-the-publisher-account). I think I can add you by user id as well.

@tlogik - Merged and deployed https://github.com/dependency-check/azuredevops/pull/145. I'll plan on letting you all take it from here for further updates and releases 🙏

**Comment by tlogik** [comment]
@ejohn20 :-) 

> @tlogik - can you confirm that you can sign into this URL: https://marketplace.visualstudio.com/manage with the email address you provided above? The marketplace is giving me an invalid domain error. Can you sign in and grab the user id from the top nav bar (https://learn.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension?view=vs-2022#troubleshoot-adding-a-user-to-the-publisher-account). I think I can add you by user id as well.

I am not able to login with the provided email.
It redirects straight to a createpublisher page.
https://marketplace.visualstudio.com/manage/createpublisher?managePageRedirect=true

I will do a bit of digging here to determine what might be the cause of that.

> @tlogik - Merged and deployed #145. I'll plan on letting you all take it from here for further updates and releases 🙏

That sounds great.
Just for brevity - what will be your role going forward - after we are all successfully onboarded? :-)

**Comment by pippolino** [comment]
Ciao @ejohn20 and @tlogik,

regarding what was said previously, if we agree, I propose to proceed using [GitHub flow](https://docs.github.com/en/get-started/quickstart/github-flow), in order to have the branch features aligned with the milestone and once completed, we can proceed with the merge into main which will trigger the automatic build.
We must therefore be careful during PR time to perform merges only on feature branches.

I await your feedback.

![image](https://github.com/dependency-check/azuredevops/assets/237308/a0a85cdf-b02b-4ab9-b97e-31c2aeb5a50c)

**Comment by Saturate** [comment]
@pippolino Sounds like a plan with milestones, and tagging of the main branch to avoid making too many releases :) I agree here.
Let me know if you need help with the azure pipeline.

I've got some initial plans, that I want to hear from all of you about as well. My first one is taking some steps in making it easier to contribute, I'm thinking setting up some linting and adding a prettier config.

I don't know how good the integration is between GitHub and azure pipelines, but if it's not working correctly or as I am thinking - I can setup some GitHub actions to make sure all PR's are building with TypeScript ect. Would be cool if the release could be done with this as well, but I'm thinking this is not for now.

But maybe let's talk about that in the PR's that I will make :)

**Comment by Saturate** [comment]
With the new release on 1/12 we are behind on the release here on GitHub. I've created a draft release, and we need to tag the main branch as well :)

**Comment by pippolino** [comment]
Ciao, 

I'm setting up the build pipeline. I think of using the following triggers, so it would be necessary for the branch names to be in the format `[0-9]+.[0-9]+.[0-9]+` (for /feature/ and /hotfix/) . Is this okay for you?

```yml
trigger:
  batch: true
  branches:
    include:
      - refs/heads/feature/*
      - refs/heads/hotfix/*
      - refs/tags/*
```

When a tag is created, starts the compilation for `Production`, generate a new version on Marketplace and create new release on GitHub.

**Comment by Saturate** [comment]
@pippolino Sounds perfect!

**Comment by ejohn20** [comment]
Updated CodeOwners file with new approvers. I think this is good to go. Feel free to ping me if you need anything else.

**Comment by pablosguajardo** [comment]
If you need help with the compilation and publishing of the extension, I can help you.
I made and use this extension to publish in MS marketplace:
https://marketplace.visualstudio.com/items?itemName=solucionespsg.GenerateAndPublishVsixToMarketplace
And this extension to version automatically:
https://marketplace.visualstudio.com/items?itemName=solucionespsg.UpdateVersionVariablesAndPackage
I made both of them.

**Comment by pippolino** [comment]
Thanks for the message.
We have the pipeline ready but we just need to fix the version number issue for prerelease environments.

**Comment by Saturate** [comment]
> Thanks for the message. We have the pipeline ready but we just need to fix the version number issue for prerelease environments.

Let me know if you need help with anything :)

**Comment by pablosguajardo** [comment]
> Thanks for the message. We have the pipeline ready but we just need to fix the version number issue for prerelease environments.

With this extension you can do it:
https://marketplace.visualstudio.com/items?itemName=solucionespsg.UpdateVersionVariablesAndPackage

An example of how to automate the upload of an app automatically to the marketplace after a commit:
<img width="363" alt="image" src="https://github.com/dependency-check/azuredevops/assets/21265093/5e4ff8b0-5895-4c58-b614-782e2792e940">
If you have to do an npm install and a run buid:
<img width="281" alt="image" src="https://github.com/dependency-check/azuredevops/assets/21265093/1f73eee8-2b64-49a2-8ae6-134e2715ff7f">

in yaml:

# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'Major' was defined in the Variables tab
# Variable 'Minor' was defined in the Variables tab
# Variable 'Patch' was defined in the Variables tab
# Variable 'VersionTag' was defined in the Variables tab
# Variable Group 'Seguridad' was defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
    persistCredentials: True
  - task: solucionespsg.UpdateVersionVariablesAndPackage.psg.UpdateVersionVariablesAndPackage.UpdateVersionVariablesAndPackage@0
    displayName: Update Version Variables And Package
  - task: qetza.replacetokens.replacetokens-task.replacetokens@5
    displayName: Replace tokens in **/*.json
    inputs:
      targetFiles: '**/*.json'
      tokenPattern: octopus
      tokenPrefix: '"'
      tokenSuffix: '": "0.0.1"'
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      verbose: false
      customCommand: run build
  - task: solucionespsg.GenerateAndPublishVsixToMarketplace.psg.GenerateAndPublishVsixToMarketplace.GenerateAndPublishVsixToMarketplace@0
    displayName: Generate and publish vsix to Marketplace
    inputs:
      TypeScriptCompile: No
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: vsxi'
    inputs:
      ArtifactName: vsxi
...

Here are the published extensions:

<img width="234" alt="image" src="https://github.com/dependency-check/azuredevops/assets/21265093/0ca50d9b-7529-4b7a-a3e4-dfb72ada6186">
