### ISSUE TITLE
CLI 9.0.0 seems to require a DB purge

### ISSUE THREAD

**Issue by LucaBlackDragon** [dependency-check/azuredevops#140]
See original issue [here](https://github.com/jeremylong/DependencyCheck/issues/6103) and error log [here](https://gist.github.com/LucaBlackDragon/b35d7c418ca72f5dabed145d032fa5a0).

**Comment by jeremylong** [comment]
see https://github.com/jeremylong/DependencyCheck#900-upgrade-notice

**Comment by pippolino** [comment]
As @jeremylong suggested, a db purge is needed for upgrade to version 9
