### ISSUE TITLE
Allow multiple --exclude

### ISSUE THREAD

**Issue by frbar** [dependency-check/azuredevops#15]
Current task is limited to one `--exclude` parameter. Can't it use a multi-line list or do a split on a delimiter?

I can only think of one workaround: deleting files / directory that need to be excluded.

**Comment by frbar** [comment]
It took me some time but with Additional Arguments, it works as expected. 

![image](https://user-images.githubusercontent.com/16399900/66913312-ab921300-f014-11e9-8897-b54bf6689156.png)

**Comment by ejohn20** [comment]
Closing this question.
