### ISSUE TITLE
Java Not Found

### ISSUE THREAD

**Issue by ejohn20** [dependency-check/azuredevops#16]
Submitted from Marina Radcke:

Running the task using a Windows Server 2019 agent leads to the error: 

```
'java' is not recognized as an internal or external command, operable program or batch file.
```

I get the same error when running the dependency-check.bat file (downloaded from OWASP) in a Command-Line task. Java is installed, running `java -version` in Command Prompt shows the version, and running dependency-check.bat directly on the server is working, too.

**Comment by ejohn20** [comment]
Solved by adding environment variable `JAVACMD` to the server and setting it to `C:\PROGRA~2\Java\jre1.8.0_211\bin`. 

It is important to use PROGRA~2, otherwise, the spaces in "Program Files (x86)" cause trouble.

**Comment by ejohn20** [comment]
Is this issue occurring on a self hosted 2019 build server? Or an Azure-hosted build agent?

**Comment by mradckeIRT** [comment]
It's a self-hosted 2019 build server.

**Comment by ejohn20** [comment]
Ok, perfect. thanks for letting us know about this scenario.

I'm going to close this issue.
