### ISSUE TITLE
6.2.1 Fails: #[error]Not found Dependency Check installer: D:\a\1\s\dependency-check

### ISSUE THREAD

**Issue by Wes-Love** [dependency-check/azuredevops#161]
**Describe the bug**
6.2.1 Fails with the error : #[error]Not found Dependency Check installer: D:\a\1\s\dependency-check

**To Reproduce**
1. Run a build including dependancy checker ( I am using the Azure Build Agent)

**Expected behavior**
It does not fail

**Logs**
Full Log:

Starting: Dependency Check
==============================================================================
Task         : OWASP Dependency Check
Description  : Dependency Check is a Software Composition Analysis (SCA) tool that attempts to detect publicly disclosed vulnerabilities contained within a project's dependencies.
Version      : 6.2.1
Author       : Dependency Check
Help         : [More Information](https://github.com/dependency-check/azuredevops)
==============================================================================
Starting Dependency Check...
Setting report directory to D:\a\1\TestResults\dependency-check
Creating report directory at D:\a\1\TestResults\dependency-check
Not found Dependency Check installer: D:\a\1\s\dependency-check
##[error]Not found Dependency Check installer: D:\a\1\s\dependency-check
##[error]Unhandled error condition detected.
Ending Dependency Check...
Finishing: Dependency Check

**Additional context**
this was working 1 hr ago with 6.2.0

**Comment by AFAde** [comment]
Experiencing the same problem too

**Comment by jepp-igus** [comment]
Same problem on linux based machines
![image](https://github.com/dependency-check/azuredevops/assets/59566036/21d8131e-2cd6-4624-b06b-f0dbb5ceba77)

Rolled back to previous version.

**Comment by ajeckmans** [comment]
Same here :)

**Comment by DmitryKozlovVentionteams** [comment]
Same issue...
We'd highly appreciate if it can be fixed asap...

**Comment by jepp-igus** [comment]
Workaround:

Changing the task version from
```yaml
- task: dependency-check-build-task@6
```
to 

```yaml
- task: dependency-check-build-task@6.2.0
```
will do the trick until a hotfix has been released...

**Comment by ajeckmans** [comment]
6.2.0 also has an open issue (#158) so I went to 6.1.3. This is not possible for non-yaml pipelines btw.

**Comment by DmitryKozlovVentionteams** [comment]
> 6.2.0 also has an open issue (#158) so I went to 6.1.3. This is not possible for non-yaml pipelines btw.

Thanks @ajeckmans , this workaround works for us
(we use the only yml-pipelines)

**Comment by pippolino** [comment]
The version [6.2.3](https://github.com/dependency-check/azuredevops/releases/tag/6.2.3) has been released with a fix.

**Comment by Wes-Love** [comment]
6.2.3 fixed it for me. Thanks
