### ISSUE TITLE
Does this require java to run?

### ISSUE THREAD

**Issue by asarro** [dependency-check/azuredevops#17]
![image](https://user-images.githubusercontent.com/5725101/67575906-6d43d480-f735-11e9-82c3-3c9f08dc6bf3.png)

**Comment by ejohn20** [comment]
Yes, dependency check is written in Java. This is installed by default on the Azure hosted build agents.

If you're using your own build server, you will need to ensure it runs locally before using the extension. See the docs for install steps: https://jeremylong.github.io/DependencyCheck/.
