### ISSUE TITLE
on-premise installation error

### ISSUE THREAD

**Issue by shugdinis** [dependency-check/azuredevops#18]
I currently have an on-premise installation of Azure DevOps.  The solution was originally a TFS 2012 that was upgraded to TFS 2018.  Then in August 2019 I updated the installation to Azure DevOps and have not had any issues with functionality or plugins.  However, when I try to load the OWASP Dependency-Check.  I get an error  "Permission section could not be loaded.  Please see image attached.  Thanks
![Owasp Dependency check](https://user-images.githubusercontent.com/6187966/67895009-16247200-fb30-11e9-9a41-9cd615098160.png)

**Comment by ejohn20** [comment]
I have not seen this issue before. You may want to open a ticket with MS support to figure out what permissions are needed on your server.

**Comment by ops-ai** [comment]
I have the same problem. Uploading the vsix manually revealed the main issue, which is that the extension is too large for the configured max extension size. Still looking for a way to increase it

![upload error](https://user-images.githubusercontent.com/4156164/68477815-5eacf100-01fc-11ea-9d48-2e7eb2d25615.PNG)

**Comment by ejohn20** [comment]
This I can help with. See this issue for a resolution: https://github.com/dependency-check/azuredevops/issues/7
