### ISSUE TITLE
Example Scan Path is Incorrect

### ISSUE THREAD

**Issue by foundinhim** [dependency-check/azuredevops#19]
I really appreciate this task! Thank you. I think I found the following issue with the [example](https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck&ssr=false#overview): 

The example image shows the value `**/*csproj`:

![](https://raw.githubusercontent.com/dependency-check/azuredevops/master/screenshots/buildtask-configure.png)

Doesn't this mean scan the actual project file as a dependency rather than looking at all of the `*.dll`s used by the program? When I changed it to check the actual `*.dll`s, it found some vulnerable dependencies.

**Comment by ejohn20** [comment]
The screenshot is just showing an example how to set the --scan option. Consult the [Documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) for the valid options.

Depending on the version of .NET you are using, the .csproj scan may or may not work. In .NET Core, the .csproj files have the list of package references that need to be scanned. The example above is scanning a .NET Core project file format.

Earlier versions use the packages.config file to list the references. Even earlier versions not using the packages.config file need to have the .dll scanned to find the references.

**Comment by foundinhim** [comment]
Thank you very much :smile:

**Comment by ejohn20** [comment]
You're welcome. Let us know if you run into any issues.
