### ISSUE TITLE
CVE Data Caching

### ISSUE THREAD

**Issue by ejohn20** [dependency-check/azuredevops#2]
Right now, the job takes several minutes because it executes on a clean agent with no data files. We can't include these in the installer because it takes the installer over 100MB compressed, which exceeds our cap.

Option 1: Can / should we host these files in an Azure Blob close to the source? Should make for a very quick pull from Azure Storage onto the build agent versus downloading from MITRE. Then, it would be easy to write an Azure function to auto-update the files every night to keep them fresh. Any reason these files can't be a publicly accessible blob? 

Option 2: ????

@jeremylong

**Comment by jeremylong** [comment]
Only option would be to host the data file somewhere - but you will need a process to update the data file at least once every seven days.  From a hosting perspective - expect that this file will get downloaded frequently.

**Comment by ejohn20** [comment]
I created a CloudFront (CDN) distribution this morning backed by an S3 origin for hosting the files in my SEC540 account. The students will benefit greatly from this db cache. I'll keep an eye on costs and circle back with you.

Downloads should be working from here:
- https://dependencycheck.sec540.com/data/jsrepository.json
- https://dependencycheck.sec540.com/data/odc.mv.db

Are there any other files that need to be pulled locally for things to work?

As far as the nightly update, initial efforts this AM failed. Tried kicking off the CLI from a Powershell task in Lambda to generate the data files and push to S3; however access denied starting a process in the execution environment. Might need to actually write a Java function to call your jar file directly, store the files in the /tmp directory, and push to S3 via the SDK. I will circle back to this...might need your help referencing the dependencycheck.jar file and finding the method that `--updateonly` actually invokes.

**Comment by ejohn20** [comment]
Fun fact: Invoke-WebRequest performance sucks by default. I updated the PS script to pull down the files from the CDN and the performance actually got worse.

Google for a bit and apparently you have to set this switch to kill the progress bar and make it not suck.

```
$ProgressPreference = 'SilentlyContinue'
```

With updated files from the CDN, build time in dev is down from (5-15 min) down to sub 30s. Rolling this out shortly.

**Comment by ejohn20** [comment]
AWS CodeBuild nightly job is officially set up and configured to refresh the data files in the CDN. Closing this issue.
