### ISSUE TITLE
Permission section could not be loaded

### ISSUE THREAD

**Issue by glasssd** [dependency-check/azuredevops#24]
Hi, I was pretty excited to learn about your extension. However, when I try to install it on our on-premises Azure DevOps 2019.Update 1 (17.153.29207.5) server, I get this error message; "We've encountered an error while downloading the extension. Please try again later." on the side panel I see: "Permission section could not be loaded", which I suspect is the root issue. (screenshot attached)

I've confirmed that I can install other extensions and I can pull down the VSIX directly (without going through the Azure DevOps extension install pages). Unfortunately, with 2019, I no longer have the option to upload an extension, so I'm not able to get past this. I'd appreciate any suggestions.

![Error Screenshot](https://user-images.githubusercontent.com/8637143/71487725-82df8400-27e2-11ea-9a93-99267beba592.png)

**Comment by ejohn20** [comment]
I'm guessing this is the issue: https://github.com/dependency-check/azuredevops/issues/18

**Comment by glasssd** [comment]
That's embarrassing. I read that one, but thought it was unrelated. I completely missed that the symptoms were **exactly** the same. The registry fix did the trick.

**Comment by ejohn20** [comment]
Excellent! Glad that did the trick! :)
