### ISSUE TITLE
RE: null leading to StackOverflowError #1969 - on Azure DevOps?

### ISSUE THREAD

**Issue by tgmz** [dependency-check/azuredevops#37]
Dear Jeremy,

I'm running into the issue jeremylong/DependencyCheck#1969 on Azure Devops:

[ERROR] An error occured trying to analyze icefaces-ace-3.1.0.jar: jquery-ui.js. To resolve this error please try increasing the Java stack size to 8mb and re-run dependency-check:

Unfortunately I have no clue how to increase stack size as there is no option to do that with the  dependency-check-build-task@5:

- task: dependency-check-build-task@5
  inputs:
    projectName: 'ISP-1519-EEG'
    enableVerbose: true
    scanPath: '$(Build.SourcesDirectory)'
    format: 'HTML'

Kind regards
Tom

**Comment by jeremylong** [comment]
@ejohn20 You can likely solve this by adding a JAVA_OPTS setting:

```
export JAVA_OPTS=-Xss8192k
```

**Comment by ejohn20** [comment]
I was going to ask if this was an environment variable or a switch that can passed to the .bat file? 

- An env var requires a package update. 

- Additional switches can be passed via the Additional Arguments input field.

**Comment by jeremylong** [comment]
Unfortunately, this can't be done via switches passed to the CLI.  I think this will require a package update.

**Comment by ejohn20** [comment]
@tgmz Azure DevOps extension updated w/ the new env var. Diff here: https://github.com/dependency-check/azuredevops/pull/39

Can you see if this helps?
