### ISSUE TITLE
Installer Download Fails

### ISSUE THREAD

**Issue by ejohn20** [dependency-check/azuredevops#44]
@jeremylong This error seems to be popping up today downloading the latest installer. I noticed this in `brew` as well as the extension. Any ideas?

https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2-release.zip

**Comment by jeremylong** [comment]
Rate limit from bintray - too many downloads in the free tier.  Apparently the CLI was downloaded over 110k times in the last 30 days.

**Comment by HanumanJat8698** [comment]
> Rate limit from bintray - too many downloads in the free tier. Apparently the CLI was downloaded over 110k times in the last 30 days.

hi @jeremylong 
As I can see now, the OWASP dependency task working fine with Azure DevOps. I am not getting this error now.
Are we in a good position to use it going forward?

**Comment by ejohn20** [comment]
OK - got it. The package is clearly downloaded often, but could also be partially related to a change I made to the Azure extension to reduce the extension size. It now downloads and installs the binaries on the fly each build, which will increase the number of downloads. Do I need to re-think this, or were you able to bump up to a tier with more downloads available?

**Comment by jeremylong** [comment]
The binary is going to have to be downloaded either way - I'd vote to not download it each time.  I'm also looking into changing to use github actions and publishing the CLI in the release artifacts so there is more then one location...

**Comment by timClyburn** [comment]
@jeremylong this seems to be an issue again. In azure devops I get a forbidden (403) error. Checking directly on the download link directly gives the same error.

**Comment by ejohn20** [comment]
#47 was opened for hopefully correcting this long term.
