### ISSUE TITLE
Update Download Links - New Version of ODC

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/azuredevops#47]
I know this should be a PR...  A new version of ODC was released - in addition we would prefer users to download the CLI from the github release rather than bintray due to bandwidth restrictions.

Please update:

https://github.com/dependency-check/azuredevops/blob/7580de253ae592e894d8fb8bb7bc97bc77887839/build/data-cache/data-cache.sh#L9

To point to the GitHub release to avoid capacity issues at bintray:

```
curl -sLo ./dependency-check-$VERSION-release.zip https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip"
```

Additionally, update:
https://github.com/dependency-check/azuredevops/blob/360d647327c719d592888a15f0ba25b204fe3d96/src/Tasks/dependency-check-build-task/dependency-check-build-task.ps1#L119-L120

To:
```
Invoke-WebRequest "https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip" -OutFile "dependency-check-6.0.2-release.zip" 
Expand-Archive -Path dependency-check-6.0.2-release.zip -DestinationPath . -Force
```

**Comment by ojasp** [comment]
@jeremylong , any timeline for when we can upgrade our task with this fix? All of our Dependency checker tasks are failing with a 403 because of this.

**Comment by ejohn20** [comment]
Working on it. Azure went down yesterday, which made it difficult to build / test. Should be today sometime.

**Comment by aspoddar** [comment]
Even after adding the lines for DependencyCheck v6.0.2, still getting the 403 ,forbidden error

**Comment by ejohn20** [comment]
I'm going to need the full scan output to trouble shoot this.

**Comment by ojasp** [comment]
> Working on it. Azure went down yesterday, which made it difficult to build / test. Should be today sometime.

Works now. Thanks for the quick turnaround.

**Comment by aspoddar** [comment]
today i am getting [ERROR] Error generating the report for RFPM-V2.0-UI-Dependency-Check
2020-09-30T04:54:10.5266725Z Dependency Check completed with exit code -12. Please suggest
