### ISSUE TITLE
Custom Installer Repository Support

### ISSUE THREAD

**Issue by ejohn20** [dependency-check/azuredevops#52]
New field for Dependency Check installer location that can override the default pull from GH releases.

**Comment by ejohn20** [comment]
This is in develop. Waiting for confirmation from @DeSpalis that the implementation works in dev before promoting.

**Comment by DeSpalis** [comment]
We tested it out and it's working as intended. Thanks for the help.

**Comment by ejohn20** [comment]
Merging into the main branch.
