### ISSUE TITLE
Database caching for Azure Pipelines

### ISSUE THREAD

**Issue by rossbeehler** [dependency-check/azuredevops#54]
We have an Azure DevOps setup where there are two self-hosted VMs running 16 agents.  The default behavior is to store the databases in C:\agent_work[number]\\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\\[version]\dependency-check\data.  This means we have 16 copies of the database across those 2 VMs.  When the default 4 hour window for NVD is crossed, 16 builds have to pay a penalty to check for updates (takes like 8 minutes!), and there's other database maintenance tasks that feel like they are happening too much.

Aside from tweaking arguments like cveValidForHours, is there anything we can do either with dependency-check or Azure Pipelines to limit builds throughout the day from experiencing large wait times.  For example, can we move to one database per VM, but then is that safe from a concurrency perspective with 8 agents running per VM?

**Comment by ejohn20** [comment]
The `Local Install Path` option allows you to place the installer in a central location on the build machine for use by each agent. This will create a centralized data directory on the VM.

We have a job that runs dependency check each night using the `dependency-check.sh --updateonly` switch to maintain and update the files in the data directory.

The extension can then use the `--noupdate` switch in the Additional Arguments field to disable updates during the scans.

**Comment by rossbeehler** [comment]
Excellent suggestion.  We'll give this a whirl.
