### ISSUE TITLE
By default download latest 6.x version of OWASP check

### ISSUE THREAD

**Issue by Cultti** [dependency-check/azuredevops#59]
Currently task downloads version 6.0.2 which is quite old (Released Sep 2020). Latest release is 6.1.1 and even the task runner complaints that we should upgrade the version:
```
[WARN] A new version of dependency-check is available. Consider updating to version 6.1.1.
```

My suggestion:
- By default download always latest 6.x version (Version 7 may contain breaking changes)
- Support specific version selection in current form

**Comment by ejohn20** [comment]
The current extension already has a current version field, you just need to update it.

![Screen Shot 2021-02-17 at 8 07 19 AM](https://user-images.githubusercontent.com/14187430/108215744-46ae6780-70f7-11eb-9707-eb98ef272f12.png)

The `develop` branch being worked on in #23 supports the `latest` tag for finding the latest verison.
