### ISSUE TITLE
Invoke-WebRequest causes SSL/TLS error

### ISSUE THREAD

**Issue by olaeld** [dependency-check/azuredevops#6]
Upon installing the extension and running it, I get the following error:

`Downloading Dependency Check vulnerability data...
##[error]System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
Ending Dependency Check...`

**Comment by ejohn20** [comment]
I've seen this before in PS using invoke web request when there is a policy preventing non-TLS1.2 connections. I'm guessing that this needs to be added to the script:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by ejohn20** [comment]
I've only used this task on the Hosted 2017 agents, can you confirm that it works on that one? I'll try to reproduce when i have a minute.

**Comment by olaeld** [comment]
Thanks, for getting back on this topic! Unfortunately, because of the setup of the project, I cannot easily test this on a Hosted 2017 agent.
