### ISSUE TITLE
Dependency Check Versions File Management

### ISSUE THREAD

**Issue by stephpelletier** [dependency-check/azuredevops#61]
We started having an issue last week when a team bumped their version of OWASP Dependency Check on our Azure DevOps pipeline. We were getting an error with the CPE analyzer because it failed initializer. Investigating the issue, we've discovered that when upgrading the Dependency Check version to be downloaded, all the pre-existing library and new library will be kept in the same folder and it cause an issue because some libraries were confused on with version to use.

I suggest keeping each version in a separated folder or cleaning the path where the archive will get decompressed.

**Comment by alaincroisetiere** [comment]
PR #58 seems to fix this issue. All files ares deleted except data folder. See in [dev branch](https://github.com/dependency-check/azuredevops/blob/6f789b796102a504b999d0d983ea3f2a24c87e84/src/Tasks/dependency-check-build-task/dependency-check-build-task.ts#L196-L199).

Stays tuned for next release. @ejohn20 is it planned ?
