### ISSUE TITLE
.NET AssemblyAnalyzer Error

### ISSUE THREAD

**Issue by tylercranston** [dependency-check/azuredevops#69]
The follow error is shown when running the dependency-check task on a DotNet Core project on a Windows Azure DevOps Hosted agent:

[ERROR] Could not execute .NET AssemblyAnalyzer

I added the following additional argument and it did not help:

--dotnet C:\hostedtoolcache\windows\dotnet\dotnet.exe

**Comment by ejohn20** [comment]
This might be better suited for the OWASP Dependency Check repo. Similar issue here: https://github.com/jeremylong/DependencyCheck/issues/3104

**Comment by skannan86** [comment]
Is there a solution for this issue? I'm facing the same issue when using it along with .net 5. Please advise. Thanks.
