### ISSUE TITLE
Azure CI OWASP Dependency check task failing to download

### ISSUE THREAD

**Issue by milyas-salik** [dependency-check/azuredevops#90]
I installed the dependency check extension for my Azure CI. As mentioned in the link : https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck&ssr=false#qna
I followed the steps mentioned, but getting the below issue..

**Hostname/IP doesn't match certificate's altnames: "Host: api.github.com. is not in the cert's altnames: DNS:*.ABC.com, DNS:ABC.com"
Unhandled error condition detected.**

Please do the needful.

**Comment by ejohn20** [comment]
Are you running the extension on premise or on an Azure hosted builder? I'm guessing this is due to running on prem behind a network appliance that is intercepting egress traffic.

**Comment by Saturate** [comment]
Closing this due to no response and inactivity.
