### ISSUE TITLE
DependencyCheck 7.0.0 breaking change breaks DevOps task

### ISSUE THREAD

**Issue by mikeolasz** [dependency-check/azuredevops#99]
The new [release](https://github.com/jeremylong/DependencyCheck/releases/tag/v7.0.0) of DependencyCheck causes pipelines to break if the owaspVersion parameter is not explicitly set to older version than 7.0.0. 

The release notes mention a database purge but in this case it's not clear how to do so.

Any ideas on how to keep using the latest version of DependencyCheck with Azure DevOps?

**Comment by hkillp** [comment]
how to delete related database ?

**Comment by iggymiggy** [comment]
I was able to purge the database by adding option `--purge` into additional arguments and running the pipeline with it once. Then I removed the option and the version 7.0.0. of Dependency Check kept working without errors.

**Comment by ejohn20** [comment]
@iggymiggy Thank you for posting the solution to this. This appears to only impact on-prem runners that have the database cached from a previous execution. 

This can also be solved by connecting to you runner and deleting the data directory inside the dependency check installation folder. On the next execution, the data directory will be repopulated with the new schema. 

Closing this issue.
